name: Daily PDF Mail

on:
  schedule:
    - cron: '30 14 * * *' # 8 PM IST

  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
    
      - name: Install Python packages
        run: |
          pip install -r requirements.txt
    
      - name: Install Playwright Browsers
        run: |
          playwright install --with-deps chromium
    
      - name: Run Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          PYTHONUNBUFFERED: "1"
        run: python -u main.py

      - name: Commit updated state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # add all state files
          git add engine/data/state/

          # commit only if there are changes
          git diff --cached --quiet || git commit -m "chore: update state [skip ci]"

          # push changes using built-in token auth
          git push
